spring:
  datasource:
    url: jdbc:mysql://monorail.proxy.rlwy.net:33473/railway
    username: root
    password: kmJUToHPsPVuJPeoWTctZFcZpvTDZOnX
    name: ecommerceDB

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes